### ISSUE TITLE
Follow-scroll PiP: content can't be shown once scrolled off-screen

### ISSUE THREAD

**Issue by anujeet98** [anujeet98/snipview#20]
## Context

#16 (\`feat/region-capture-follow-scroll\`) tried to make the cropped PiP follow the selected page region as the page scrolls, so you keep seeing the same content instead of a fixed viewport rectangle. It's reverted for now in #20 pending a real design here.

## What actually happens

Tested on CoinDCX, a ChatGPT thread, and a plain scrollable company page. In every case, once the selected region scrolls out of the *visible* viewport, the PiP starts showing drifting/wrong content instead of continuing to track the target.

## Root cause

The captured video stream (via \`chrome.tabCapture\`, and this holds for \`getDisplayMedia\`-based Region Capture too) only ever contains what's currently painted in the browser's visible viewport — browsers don't render/paint content once it's scrolled off-screen. The crop code recomputes the target's position each frame from \`getBoundingClientRect()\` and clamps it into the captured frame's bounds. While the target is on-screen this works, but the instant it scrolls out of view there's no pixel data for it anymore, so the clamp grabs whatever's at the nearest edge of the *current* viewport — which keeps changing as you scroll, looking exactly like the PiP has started scrolling with the page.

This isn't fixable by better position tracking — it's a fundamental limit of viewport-based capture. No capture technique (canvas or native Region Capture / \`cropTo\`) can show content that isn't currently being rendered.

## Options to pick from next time this is picked up

- **Freeze last good frame**: stop updating the crop once the target leaves the viewport, hold the last valid image, resume tracking once it's back in view.
- **Blank/dim with a label**: show an empty or dimmed frame with something like "out of view" while the target is off-screen.
- Something else — worth discussing scope (e.g. is "off-screen tracking" even a use case worth solving, vs. just keeping the simpler fixed-viewport crop from before #16 and calling it done).

## Related

- Introduced in #16 (9c24205)
- Reverted in #20
- The unrelated crash this surfaced (\`cropTo is not a function\`, SnipView not opening at all) is fixed separately in #19

**Comment by anujeet98** [comment]
Deferred out of v1 scope — not blocking first rollout. Revisit post-launch.
